# set dynamic variables depending on group membership
- name: define datacenter depending on group gridftp_hx 
  set_fact:
     datacenter: "HX"
     join_address: "193.62.194.2"
  when: '"gridftp_hx" in group_names'
  
- name: define datacenter depending on group gridftp_hx 
  set_fact:
     datacenter: "HH"
     join_address: "193.62.193.207"
  when: '"gridftp_hh" in group_names'
  
- name: install needed packages for psutil
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
  with_items:
    - httpd
    - python-pip
    - gcc
    - python-devel
  when: "'gridftp-1' not in inventory_hostname"
  
- name: install needed pip packages
  pip:
    name: psutil
  when: "'gridftp-1' not in inventory_hostname"
      
- name: configure consul agents
  template: 
     src: roles/consul-agent/templates/config.json
     dest: /opt/consul/config.json
     owner: consul
     group: consul
     mode: '0600'
  when: "'gridftp-1' not in inventory_hostname"  

- name: start consul agents
  service:
     name: consul
     state: started
  when: 
     - "'gridftp-1' not in inventory_hostname"

#- name: restart consul agents
#  service:
#     name: consul
#     state: restarted
#  when: 
#     - "'gridftp-1' not in inventory_hostname"
  
  